name: Android-apk-build

on:
  workflow_dispatch:

jobs:
  build-android:
    name: 🎉 Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Debug step to list all files and directories after checkout
      - name: List repository files
        run: ls -R
        working-directory: .

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Flutter pub get in mobile_application_store directory
      - run: flutter pub get
        working-directory: ./mobile_application_store

      # Build Android APK in mobile_application_store
      - run: flutter build apk --release
        working-directory: ./mobile_application_store

      # Rename the APK for easier identification (optional)
      - run: mv ./build/app/outputs/flutter-apk/app-release.apk ./build/app/outputs/flutter-apk/mobile_application_store-release.apk
        working-directory: ./mobile_application_store

      # Upload the APK to the release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./mobile_application_store/build/app/outputs/flutter-apk/mobile_application_store-release.apk
          tag: v1.0
          overwrite: true
          body: "This is the first release"
