name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      # Debug step to list all files and directories after checkout
      - name: List repository files
        run: ls -R
        working-directory: .

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Flutter pub get in mobile_application_store directory
      - run: flutter pub get
        working-directory: ./mobile_application_store

      # Update CocoaPods repo inside iOS directory
      - run: pod repo update
        working-directory: ./mobile_application_store/ios

      # Build iOS app without codesigning in mobile_application_store
      - run: flutter build ios --release --no-codesign
        working-directory: ./mobile_application_store

      # Create Payload directory in the build folder
      - run: mkdir Payload
        working-directory: ./mobile_application_store/build/ios/iphoneos

      # Move Runner.app into the Payload directory
      - run: mv Runner.app/ Payload
        working-directory: ./mobile_application_store/build/ios/iphoneos

      # Zip the IPA output
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: ./mobile_application_store/build/ios/iphoneos

      # Upload the IPA to the release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./mobile_application_store/build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
